apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp
  labels:
    app: restaurantapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantapp
  template:
    metadata:
      labels:
        app: restaurantapp
    spec:
      containers:
        - name: restaurantapp
          image: codedecode25/restaurant-listing-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
              valueFrom: # Get the value of environment variable from kubernetes secrets
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: restaurantdb_url
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: restaurantapp
 
